// <auto-generated />
namespace Nike_vn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditOrderIdColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditOrderIdColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202212240716541_EditOrderIdColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
