// <auto-generated />
namespace Nike_vn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addCartTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCartTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202212231720130_addCartTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
